### ISSUE TITLE
file_line does not work in version 8.6.0 (Unknown resource type)

### ISSUE THREAD

**Issue by apt4user** [puppetlabs/puppetlabs-stdlib#1430]
## Describe the Bug
I've installed the puppetlabs-stdlib 8.6.0 module and I declared the resource type "file_line" in my init.pp but I get the error: Unknown resource type: 'file_line'

I also set the include directive `include stdlib` into `site.pp` and into my puppet manifest

When I try to perform a puppet run with file_line declared in my hiera configuration file like

```
---
classes:
  - stdlib

stblib::manage::create_resources:
  file_line:
    path: 'path/to/file'
    line: 'testtestest'
```
then everything works

## Expected Behavior
I wanted to append a string to an existing file.

## Steps to Reproduce
Install the current stdlib 8.6.0 module and try to declare the resource type 'file_line'

## Environment
 - Puppet 8.6.0
 - Platform [Ubuntu 22.04]
